### ISSUE TITLE
Create configuration settings for setting the API_URL for using with fetch

### ISSUE THREAD

**Issue by iheanyi** [BlackathonBlackers/DisPiff#16]
Since `isomorphic-fetch` only supports absolute URLs, we need a way for our React app to know where to talk to.

**Comment by reggie** [comment]
>_>

**Comment by iheanyi** [comment]
@reggie - What man? This is an easily fixable problem and something we won't have to worry about until we actually deploy the app itself, lol.

**Comment by reggie** [comment]
I mean I don't even know what isomorphic-fetch is lol but only absolute URLs -_-

**Comment by iheanyi** [comment]
Aight, I lied. It was `nock` that only supported absolute URLs, but we're not using using that anymore for now, hahaha.
